apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:  
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: bitnami/mongodb:5.0.17
        ports:
        - containerPort: 27017
        env:
          - name: MONGODB_ROOT_PASSWORD
            value: root 
          # - name: MONGODB_USERNAME
          #   value: my_user 
          # - name: MONGODB_PASSWORD
          #   value: password123 
          - name: MONGODB_REPLICA_SET_MODE
            value: primary 
          - name: MONGODB_REPLICA_SET_KEY
            value: replicasetkey123
          - name: MONGODB_DATABASE
            value: "homebroker"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 4
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: trader-api
        ports:
        - containerPort: 3000
        env:
          - name: DATABASE_URL
            value: mongodb://root:root@mongodb:27017/homebroker?directConnection=true&authSource=admin
          - name: KAFKA_ENDPOINT
            value: "kafka-service:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30000
  type: NodePort
